```{r}
library(rhdf5)
library(SingleCellExperiment)
library(Seurat)
library(data.table)

library(dplyr)
library(dbplyr)
library(tidyr)
library(tibble)
library(readr)
library(ggplot2)
library(magrittr)
library(readxl)
library(stringr)
library(testit)
library(knitr)
library(ggpubr)
library(Matrix.utils)
library(S4Vectors)
library(Biobase)
library(immunedeconv)
library(data.tree)
library(rsample)
library(gridExtra)
devtools::load_all("~/Lieselore/R/Benchmark/immunedeconv")
```

```{r}
bulk_mel_1.1 = readRDS("loading_data/pseudobulk_data/bulk_melanoma_1.1.rds")
bulk_lung_2.1 = readRDS("loading_data/pseudobulk_data/bulk_lung_2.1.rds")
bulk_lung_2.2 = readRDS("loading_data/pseudobulk_data/bulk_lung_2.2.rds")

```

```{r}
true_mel_1.1 = pData(bulk_mel_1.1)%>%
   rename("B cell" = B,
         "T cell CD4+" = CD4Tconv,
         "T cell CD8+" = CD8Tex,
         "Macrophage/Monocyte" = "Mono/Macro",
         "Endothelial cell" = Endothelial,
         "uncharacterized cell" = Malignant,
         "Cancer associated fibroblast" = Fibroblasts)%>%
  t() %>%
  as_tibble(rownames="cell_type")%>%
  gather(sample, true_fraction, -cell_type)

true_lung_2.1 = pData(bulk_lung_2.1)%>%
   rename("B cell" = B,
         "T cell CD4+" = CD4Tconv,
         "T cell CD8+" = CD8T,
         "Macrophage/Monocyte" = "Mono/Macro",
         "Endothelial cell" = Endothelial,
         "uncharacterized cell" = Malignant)%>%
  t() %>%
  as_tibble(rownames="cell_type")%>%
  gather(sample, true_fraction, -cell_type)

true_lung_2.2 = pData(bulk_lung_2.2)%>%
   rename("B cell" = B,
         "T cell CD4+" = CD4Tconv,
         "T cell CD8+" = CD8Tex,
         "Macrophage/Monocyte" = "Mono/Macro",
         "Endothelial cell" = Endothelial,
         "uncharacterized cell" = Malignant,
         "NK cell" = NK,
         "Dendritic cell" = DC,
         "Cancer associated fibroblast" = Fibroblasts)%>%
  t() %>%
  as_tibble(rownames="cell_type")%>%
  gather(sample, true_fraction, -cell_type)

```

```{r}
res_mel_1.1 = read.delim("~/Lieselore/R/Signature matrix/epic_results/EPIC_mel_1.1_melREF_nocan.txt")%>%
  column_to_rownames("sampleID")%>%
  rename("B cell" = B,
         "T cell CD4+" = CD4Tconv,
         "T cell CD8+" = CD8Tex,
         "Macrophage/Monocyte" = "Mono.Macro",
         "Endothelial cell" = Endothelial,
         "uncharacterized cell" = otherCells,
         "Cancer associated fibroblast" = Fibroblasts)%>%
  t()%>%
  as.data.frame()%>%
  rownames_to_column("cell_type")%>%
  gather(sample,fraction,-cell_type)%>%
  mutate(method= "Custom gene list")

res_mel_1.1_tisch = read.delim("~/Lieselore/R/Signature matrix/epic_results/EPIC_mel_1.1_melREF_tisch.txt")%>%
  column_to_rownames("sampleID")%>%
  rename("B cell" = B,
         "T cell CD4+" = CD4Tconv,
         "T cell CD8+" = CD8Tex,
         "Macrophage/Monocyte" = "Mono.Macro",
         "Endothelial cell" = Endothelial,
         "uncharacterized cell" = otherCells,
         "Cancer associated fibroblast" = Fibroblasts)%>%
  t()%>%
  as.data.frame()%>%
  rownames_to_column("cell_type")%>%
  gather(sample,fraction,-cell_type)%>%
  mutate(method= "TISCH gene list")

```

```{r}
both = inner_join(res_mel_1.1, true_mel_1.1)

both_tisch = inner_join(res_mel_1.1_tisch, true_mel_1.1)
```
```{r}
all_results = bind_rows(both, both_tisch)

all_results %>%
  ggplot(aes(x=true_fraction, y=fraction)) +
  facet_grid(method ~ cell_type, scales="free") +
  geom_point() +
  stat_smooth(aes(color=method), method="lm") +
  scale_x_continuous(breaks=c(.2, .3)) +
  stat_cor(aes(label = ..r.label..),size = 3,label.y.npc="top", label.x.npc = "left")+
  scale_color_discrete(name = "Gene list")+
  ggtitle("Melanoma 1.1")+
  xlab("True fraction")+
  ylab("Fraction")->p1

ggsave("plot_effect_gene_list.png", width = 16, height = 10)
```

```{r}
res_lung_2.1 = read.delim("~/Lieselore/R/Signature matrix/epic_results/EPIC_lung_2.1_melREF_nocan.txt")%>%
  column_to_rownames("sampleID")%>%
  rename("B cell" = B,
         "T cell CD4+" = CD4Tconv,
         "T cell CD8+" = CD8Tex,
         "Macrophage/Monocyte" = "Mono.Macro",
         "Endothelial cell" = Endothelial,
         "uncharacterized cell" = otherCells,
         "Cancer associated fibroblast" = Fibroblasts)%>%
  t()%>%
  as.data.frame()%>%
  rownames_to_column("cell_type")%>%
  gather(sample,fraction,-cell_type)%>%
  mutate(method= "Custom gene list")

res_lung_2.1_tisch = read.delim("~/Lieselore/R/Signature matrix/epic_results/EPIC_lung_2.1_melREF_tisch.txt")%>%
  column_to_rownames("sampleID")%>%
  rename("B cell" = B,
         "T cell CD4+" = CD4Tconv,
         "T cell CD8+" = CD8Tex,
         "Macrophage/Monocyte" = "Mono.Macro",
         "Endothelial cell" = Endothelial,
         "uncharacterized cell" = otherCells,
         "Cancer associated fibroblast" = Fibroblasts)%>%
  t()%>%
  as.data.frame()%>%
  rownames_to_column("cell_type")%>%
  gather(sample,fraction,-cell_type)%>%
  mutate(method= "TISCH gene list")


```

```{r}
both_lung =inner_join(res_lung_2.1, true_lung_2.1)

both_lung_tisch = inner_join(res_lung_2.1_tisch, true_lung_2.1)
```
```{r}
all_results_lung = bind_rows(both_lung,both_lung_tisch)

all_results_lung %>%
  ggplot(aes(x=true_fraction, y=fraction)) +
  facet_grid(method ~ cell_type, scales="free") +
  geom_point() +
  stat_smooth(aes(color=method), method="lm") +
  scale_x_continuous(breaks=c(.2, .3)) +
   stat_cor(aes(label = ..r.label..),size = 3,label.y.npc="top", label.x.npc = "left")+
  scale_color_discrete(name = "Gene list")+
  ggtitle("Lung 2.1")+
  xlab("True fraction")+
  ylab("Fraction")-> p2

ggsave("plot_effect_gene_list_lung.png", width = 16, height = 10)

```

```{r}
res_lung_2.2 = read.delim("~/Lieselore/R/Signature matrix/epic_results/EPIC_lung_2.2_melREF_nocan.txt")%>%
  column_to_rownames("sampleID")%>%
  rename("B cell" = B,
         "T cell CD4+" = CD4Tconv,
         "T cell CD8+" = CD8Tex,
         "Macrophage/Monocyte" = "Mono.Macro",
         "Endothelial cell" = Endothelial,
         "uncharacterized cell" = otherCells,
         "Cancer associated fibroblast" = Fibroblasts)%>%
  t()%>%
  as.data.frame()%>%
  rownames_to_column("cell_type")%>%
  gather(sample,fraction,-cell_type)%>%
  mutate(method= "Custom gene list")

res_lung_2.2_tisch = read.delim("~/Lieselore/R/Signature matrix/epic_results/EPIC_lung_2.2_melREF_tisch.txt")%>%
  column_to_rownames("sampleID")%>%
  rename("B cell" = B,
         "T cell CD4+" = CD4Tconv,
         "T cell CD8+" = CD8Tex,
         "Macrophage/Monocyte" = "Mono.Macro",
         "Endothelial cell" = Endothelial,
         "uncharacterized cell" = otherCells,
         "Cancer associated fibroblast" = Fibroblasts)%>%
  t()%>%
  as.data.frame()%>%
  rownames_to_column("cell_type")%>%
  gather(sample,fraction,-cell_type)%>%
  mutate(method= "TISCH gene list")


```

```{r}
both_lung_2.2 =inner_join(res_lung_2.2, true_lung_2.2)

both_lung_2.2_tisch = inner_join(res_lung_2.2_tisch, true_lung_2.2)
```


```{r}
all_results_lung_2.2 = bind_rows(both_lung_2.2,both_lung_2.2_tisch)

all_results_lung_2.2 %>%
  ggplot(aes(x=true_fraction, y=fraction)) +
  facet_grid(method ~ cell_type, scales="free") +
  geom_point() +
  stat_smooth(aes(color=method), method="lm") +
  scale_x_continuous(breaks=c(.2, .3)) +
  stat_cor(aes(label = ..r.label..),size = 3,label.y.npc="top", label.x.npc = "left")+
  scale_color_discrete(name = "Gene list")+
  ggtitle("Lung 2.2")+
  xlab("True fraction")+
  ylab("Fraction")->p3

ggsave("plot_effect_gene_list_lung_2.2_tisch.png", width = 16, height = 10)

```

```{r}
library(patchwork)

p1 / p2 / p3 +
  plot_annotation(tag_levels = 'a')

ggsave("plot_effect_gene_list_all.png", width = 16, height = 20)
```

