effect of cancer in signature matrix

```{r}
library(rhdf5)
library(SingleCellExperiment)
library(Seurat)
library(data.table)

library(dplyr)
library(dbplyr)
library(tidyr)
library(tibble)
library(readr)
library(ggplot2)
library(magrittr)
library(readxl)
library(stringr)
library(testit)
library(knitr)
library(ggpubr)
library(Matrix.utils)
library(S4Vectors)
library(Biobase)
library(immunedeconv)
library(data.tree)
library(rsample)
devtools::load_all("~/Lieselore/R/Benchmark/immunedeconv")
```


#loading data
```{r}
bulk_lung_2.1 = readRDS("loading_data/pseudobulk_data/bulk_lung_2.1.rds")
```

#true fractions van simulated samples
```{r}

true_lung_2.1 = pData(bulk_lung_2.1)%>%
   rename("B cell" = B,
         "T cell CD4+" = CD4Tconv,
         "T cell CD8+" = CD8T,
         "Macrophage/Monocyte" = "Mono/Macro",
         "Endothelial cell" = Endothelial,
         "Cancer cell" = Malignant)%>%
  t() %>%
  as_tibble(rownames="cell_type")%>%
  gather(sample, true_fraction, -cell_type)





ggplot(true_lung_2.1, aes(x=sample, y=true_fraction)) +
  geom_bar(aes(fill=cell_type), stat="identity") +
  theme(axis.text.x=element_text(angle = 90, vjust = 0.5, hjust=1)) 
```


```{r}
#niet nodig
res_orig = deconvolute(bulk_lung_2.1,"epic", tumor = TRUE, scale_mrna = FALSE, column = "gene_symbol")

cell_types_epic = c("B cell", "Macrophage/Monocyte", "T cell CD4+",
                    "T cell CD8+","Endothelial cell","Cancer associated fibroblast","Cancer cell")
                  

res_orig2 = map_result_to_celltypes(res_orig,cell_types_epic)%>%
  rownames_to_column("cell_type")%>%
  gather(sample,fraction,-cell_type)%>%
  mutate(method = "Original signature")

both_orig = inner_join(res_orig2,true_lung_2.1,by=c("sample","cell_type"))

ggplot(both_orig , aes(x=true_fraction, y=fraction)) +
  labs(title = "EPIC original")+
  facet_grid(~cell_type, scales="free") +
  geom_point() +
  stat_smooth(method="lm") +
  stat_cor()
```
#epic met melanoma signature WITH cancer
```{r}

res_lung_2.1 = read.delim("~/Lieselore/R/Signature matrix/epic_results/EPIC_lung_melREF2.txt")%>%
  column_to_rownames("sampleID")%>%
  rename("B cell" = B,
         "T cell CD4+" = CD4Tconv,
         "T cell CD8+" = CD8Tex,
         "Macrophage/Monocyte" = "Mono.Macro",
         "Endothelial cell" = Endothelial,
         "Cancer cell" = Malignant,
         "Cancer associated fibroblast" = Fibroblasts)%>%
  t()%>%
  as.data.frame()%>%
  rownames_to_column("cell_type")%>%
  gather(sample,fraction,-cell_type)%>%
  mutate(method= "mel_sig on lung 2.1")


  
  
                                                                                                                                                                                                                                      
both_lung_2.1 = inner_join(res_lung_2.1,true_lung_2.1,by=c("sample","cell_type"))
                                                                                                                                                                                                                                

ggplot(both_lung_2.1, aes(x=true_fraction, y=fraction)) +
  labs(title = "EPIC with mel sig with cancer")+
  facet_grid(~cell_type, scales="free") +
  geom_point() +
  stat_smooth(method="lm") +
  stat_cor()



```

```{r}

res_lung_nocan = read.delim("~/Lieselore/R/Signature matrix/epic_results/EPIC_lung_2.1_melREF_nocan.txt")%>%
  column_to_rownames("sampleID")%>%
  rename("B cell" = B,
         "T cell CD4+" = CD4Tconv,
         "T cell CD8+" = CD8Tex,
         "Macrophage/Monocyte" = "Mono.Macro",
         "Endothelial cell" = Endothelial,
         "Cancer cell" = otherCells,
         "Cancer associated fibroblast" = Fibroblasts)%>%
  t()%>%
  as.data.frame()%>%
  rownames_to_column("cell_type")%>%
  gather(sample,fraction,-cell_type)%>%
  mutate(method= "mel_sig_nocan on lung 2.1")

  
  
                                                                                                                                                                                                                                      
both_lung_nocan = inner_join(res_lung_nocan,true_lung_2.1,by=c("sample","cell_type"))
                                                                                                                                                                                                                                

ggplot(both_lung_nocan, aes(x=true_fraction, y=fraction)) +
  labs(title = "EPIC with melanoma signature without cancer cells")+
  facet_grid(~cell_type, scales="free") +
  geom_point() +
  stat_smooth(method="lm") +
  stat_cor()


```

#creating plot with no cancer and cancer signature
```{r}
compare_nocan= bind_rows(res_lung_2.1_2,res_lung_nocan_2)%>%
  arrange(method, cell_type, sample)

compare_nocan_with_true = inner_join(compare_nocan,true_lung_2.1,by=c("sample","cell_type"))

compare_nocan_with_true %>%
  ggplot(aes(x=true_fraction, y=fraction)) +
  facet_grid(method ~ cell_type, scales="free") +
  geom_point() +
  stat_smooth(aes(color=method), method="lm") +
  scale_x_continuous(breaks=c(.2, .3)) +
  stat_cor()

ggsave("plot_lung_with_nocancer.png", width = 20, height = 10)

```


#combining lung and melanoma plots
```{r}
compare = bind_rows(both_lung_nocan, both_lung_2.1,both_mel_nocan,both_mel_1.1)%>%
  mutate(across(method, factor, levels = c("mel_sig on melanoma 1.1", "mel_sig_nocan on melanoma 1.1",
                                           "mel_sig on lung 2.1", "mel_sig_nocan on lung 2.1")))%>%
   arrange(method, cell_type)

compare %>%
  ggplot(aes(x=true_fraction, y=fraction)) +
  facet_grid(method ~ cell_type, scales="free") +
  geom_point() +
  stat_smooth(aes(color=method), method="lm") +
  scale_x_continuous(breaks=c(.2, .3)) +
  stat_cor(aes(label = ..r.label..),size = 3,label.y.npc="top", label.x.npc = "left")+
  scale_color_discrete(name = "Method")+
  xlab("True fraction")+
  ylab("Fraction")
 

ggsave("plot_mel_lung_effect_cancer.png", width = 16, height = 10)


```

