Melanoma signature (without cancer cells!) on all datasets

```{r}
library(rhdf5)
library(SingleCellExperiment)
library(Seurat)
library(data.table)

library(dplyr)
library(dbplyr)
library(tidyr)
library(tibble)
library(readr)
library(ggplot2)
library(magrittr)
library(readxl)
library(stringr)
library(testit)
library(knitr)
library(ggpubr)
library(Matrix.utils)
library(S4Vectors)
library(Biobase)
library(immunedeconv)
library(data.tree)
library(rsample)
devtools::load_all("~/Lieselore/R/Benchmark/immunedeconv")
```

loading data
```{r}
bulk_mel_1.1 = readRDS("loading_data/pseudobulk_data/bulk_melanoma_1.1.rds")
bulk_mel_1.2 = readRDS("loading_data/pseudobulk_data/bulk_melanoma_1.2.rds")
bulk_lung_2.1 = readRDS("loading_data/pseudobulk_data/bulk_lung_2.1.rds")
bulk_lung_2.2 = readRDS("loading_data/pseudobulk_data/bulk_lung_2.2.rds")
bulk_liver_3.1 = readRDS("loading_data/pseudobulk_data/bulk_liver_3.1.rds")
bulk_neck_4.1 = readRDS("loading_data/pseudobulk_data/bulk_neck_4.1.rds")
```

true fractions
```{r}
true_mel_1.1 = pData(bulk_mel_1.1)%>%
   rename("B cell" = B,
         "T cell CD4+" = CD4Tconv,
         "T cell CD8+" = CD8Tex,
         "Macrophage/Monocyte" = "Mono/Macro",
         "Endothelial cell" = Endothelial,
         "uncharacterized cell" = Malignant,
         "Cancer associated fibroblast" = Fibroblasts)%>%
  t() %>%
  as_tibble(rownames="cell_type")%>%
  gather(sample, true_fraction, -cell_type)

true_mel_1.2 = pData(bulk_mel_1.2)%>%
   rename("B cell" = B,
         "T cell CD4+" = CD4Tconv,
         "T cell CD8+" = CD8Tex,
         "Macrophage/Monocyte" = "Mono/Macro",
         "Endothelial cell" = Endothelial,
         "uncharacterized cell" = Malignant,
         "Cancer associated fibroblast" = Fibroblasts,
         "NK cell" = NK)%>%
  t() %>%
  as_tibble(rownames="cell_type")%>%
  gather(sample, true_fraction, -cell_type)

true_lung_2.1 = pData(bulk_lung_2.1)%>%
   rename("B cell" = B,
         "T cell CD4+" = CD4Tconv,
         "T cell CD8+" = CD8T,
         "Macrophage/Monocyte" = "Mono/Macro",
         "Endothelial cell" = Endothelial,
         "uncharacterized cell" = Malignant)%>%
  t() %>%
  as_tibble(rownames="cell_type")%>%
  gather(sample, true_fraction, -cell_type)

true_lung_2.2 = pData(bulk_lung_2.2)%>%
   rename("B cell" = B,
         "T cell CD4+" = CD4Tconv,
         "T cell CD8+" = CD8Tex,
         "Macrophage/Monocyte" = "Mono/Macro",
         "Endothelial cell" = Endothelial,
         "uncharacterized cell" = Malignant,
         "NK cell" = NK,
         "Dendritic cell" = DC,
         "Cancer associated fibroblast" = Fibroblasts)%>%
  t() %>%
  as_tibble(rownames="cell_type")%>%
  gather(sample, true_fraction, -cell_type)

true_liver_3.1 = pData(bulk_liver_3.1)%>%
   rename("B cell" = B,
         "T cell CD4+" = CD4Tconv,
         "Macrophage/Monocyte" = "Mono/Macro",
         "Endothelial cell" = Endothelial,
         "uncharacterized cell" = Malignant,
         "Cancer associated fibroblast" = Fibroblasts)%>%
  mutate(`T cell CD8+` = CD8T + CD8Tex)%>%
  t() %>%
  as_tibble(rownames="cell_type")%>%
  gather(sample, true_fraction, -cell_type)

true_neck_4.1 = pData(bulk_neck_4.1)%>%
   rename(
         "T cell CD4+" = CD4Tconv,
         "Macrophage/Monocyte" = "Mono/Macro",
         "Endothelial cell" = Endothelial,
         "uncharacterized cell" = Malignant,
         "Cancer associated fibroblast" = Fibroblasts)%>%
  mutate(`T cell CD8+` = CD8T + CD8Tex)%>%
  t() %>%
  as_tibble(rownames="cell_type")%>%
  gather(sample, true_fraction, -cell_type)

```

results with epic
```{r}

res_mel_1.1 = read.delim("~/Lieselore/R/Signature matrix/epic_results/EPIC_mel_1.1_melREF_nocan.txt")%>%
  column_to_rownames("sampleID")%>%
  rename("B cell" = B,
         "T cell CD4+" = CD4Tconv,
         "T cell CD8+" = CD8Tex,
         "Macrophage/Monocyte" = "Mono.Macro",
         "Endothelial cell" = Endothelial,
         "uncharacterized cell" = otherCells,
         "Cancer associated fibroblast" = Fibroblasts)%>%
  t()%>%
  as.data.frame()%>%
  rownames_to_column("cell_type")%>%
  gather(sample,fraction,-cell_type)%>%
  mutate(method= "Melanoma 1.1")

res_mel_1.2 = read.delim("~/Lieselore/R/Signature matrix/epic_results/EPIC_mel_1.2_melREF_nocan.txt")%>%
  column_to_rownames("sampleID")%>%
  rename("B cell" = B,
         "T cell CD4+" = CD4Tconv,
         "T cell CD8+" = CD8Tex,
         "Macrophage/Monocyte" = "Mono.Macro",
         "Endothelial cell" = Endothelial,
         "uncharacterized cell" = otherCells,
         "Cancer associated fibroblast" = Fibroblasts)%>%
  t()%>%
  as.data.frame()%>%
  rownames_to_column("cell_type")%>%
  gather(sample,fraction,-cell_type)%>%
  mutate(method= "Melanoma 1.2")

res_lung_2.1 = read.delim("~/Lieselore/R/Signature matrix/epic_results/EPIC_lung_2.1_melREF_nocan.txt")%>%
  column_to_rownames("sampleID")%>%
  rename("B cell" = B,
         "T cell CD4+" = CD4Tconv,
         "T cell CD8+" = CD8Tex,
         "Macrophage/Monocyte" = "Mono.Macro",
         "Endothelial cell" = Endothelial,
         "uncharacterized cell" = otherCells,
         "Cancer associated fibroblast" = Fibroblasts)%>%
  t()%>%
  as.data.frame()%>%
  rownames_to_column("cell_type")%>%
  gather(sample,fraction,-cell_type)%>%
  mutate(method= "Lung 2.1")

res_lung_2.2 = read.delim("~/Lieselore/R/Signature matrix/epic_results/EPIC_lung_2.2_melREF_nocan.txt")%>%
  column_to_rownames("sampleID")%>%
  rename("B cell" = B,
         "T cell CD4+" = CD4Tconv,
         "T cell CD8+" = CD8Tex,
         "Macrophage/Monocyte" = "Mono.Macro",
         "Endothelial cell" = Endothelial,
         "uncharacterized cell" = otherCells,
         "Cancer associated fibroblast" = Fibroblasts)%>%
  t()%>%
  as.data.frame()%>%
  rownames_to_column("cell_type")%>%
  gather(sample,fraction,-cell_type)%>%
  mutate(method= "Lung 2.2")

res_liver_3.1 = read.delim("~/Lieselore/R/Signature matrix/epic_results/EPIC_liver_3.1_melREF_nocan.txt")%>%
  column_to_rownames("sampleID")%>%
  rename("B cell" = B,
         "T cell CD4+" = CD4Tconv,
         "T cell CD8+" = CD8Tex,
         "Macrophage/Monocyte" = "Mono.Macro",
         "Endothelial cell" = Endothelial,
         "uncharacterized cell" = otherCells,
         "Cancer associated fibroblast" = Fibroblasts)%>%
  t()%>%
  as.data.frame()%>%
  rownames_to_column("cell_type")%>%
  gather(sample,fraction,-cell_type)%>%
  mutate(method= "Liver 3.1")

res_neck_4.1 = read.delim("~/Lieselore/R/Signature matrix/epic_results/EPIC_neck_4.1_melREF_nocan.txt")%>%
  column_to_rownames("sampleID")%>%
  rename("B cell" = B,
         "T cell CD4+" = CD4Tconv,
         "T cell CD8+" = CD8Tex,
         "Macrophage/Monocyte" = "Mono.Macro",
         "Endothelial cell" = Endothelial,
         "uncharacterized cell" = otherCells,
         "Cancer associated fibroblast" = Fibroblasts)%>%
  t()%>%
  as.data.frame()%>%
  rownames_to_column("cell_type")%>%
  gather(sample,fraction,-cell_type)%>%
  mutate(method= "Head and neck 4.1")

```


```{r}
both_mel_1.1 = inner_join(res_mel_1.1,true_mel_1.1,by=c("sample","cell_type"))                                                      
both_mel_1.2 = inner_join(res_mel_1.2,true_mel_1.2,by=c("sample","cell_type"))                                                     
both_lung_2.1 = inner_join(res_lung_2.1,true_lung_2.1,by=c("sample","cell_type"))

both_lung_2.2 = inner_join(res_lung_2.2,true_lung_2.2,by=c("sample","cell_type"))

both_liver_3.1 = inner_join(res_liver_3.1,true_liver_3.1,by=c("sample","cell_type"))

both_neck_4.1 = inner_join(res_neck_4.1,true_neck_4.1,by=c("sample","cell_type"))
```

```{r}
all_results= bind_rows(both_mel_1.1,both_mel_1.2,both_lung_2.1,both_lung_2.2,
                       both_liver_3.1,both_neck_4.1)%>%
  mutate(across(method, factor, levels = c("Melanoma 1.1", "Melanoma 1.2", "Lung 2.1", "Lung 2.2",
                                           "Liver 3.1","Head and neck 4.1")))%>%
  
  arrange(method, cell_type, sample)



all_results %>%
  ggplot(aes(x=true_fraction, y=fraction)) +
  facet_grid(method ~ cell_type, scales="free") +
  geom_point() +
  stat_smooth(aes(color=method), method="lm") +
  scale_x_continuous(breaks=c(.2, .3)) +
  stat_cor(aes(label = ..r.label..),size = 3,label.y.npc="middle", label.x.npc = "left")+
  scale_color_discrete(name = "Simulated samples")+
  xlab("True fraction")+
  ylab("Fraction")



ggsave("plot_all_datasets_melanoma_1.1_signature1.png", width = 16, height = 10)

```

```{r}

correlations = all_results %>%
  group_by(cell_type, method) %>%
  summarize(cor = cor(fraction,true_fraction)) 
  
  
correlations %>%
  ggplot(aes(x=cor, y=cell_type))+
  geom_bar(stat= "identity", aes(fill =cell_type), show.legend = FALSE)+
  facet_wrap(~method, nrow = 2) +
  xlab("R value")+
  ylab("")+
  theme(text = element_text(size = 15))
  
  
 ggsave("plot_correlation_melanoma_1.1_signature.png", width = 16, height = 10)

  


```




